// Code generated by goctl. DO NOT EDIT.
package types

type FastLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type FastLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type EnterServerReq struct {
	ServerCode string `json:"serverCode"`
}

type EnterServerResp struct {
	ReturnCode int64 `json:"returnCode"`
}

type LoginServerReq struct {
	ServerId string `json:"serverId"`
}

type LoginServerResp struct {
	ReturnCode int64  `json:"returnCode"`
	ServerCode string `json:"serverCode"`
}
