// Code generated by goctl. DO NOT EDIT.
package types

type FastLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type FastLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type EnterServerReq struct {
	ServerId    string `json:"serverId"`
	AccessToken string `json:"accessToken"`
}

type EnterServerResp struct {
	ServerToken string `json:"serverToken"`
}
