// Code generated by goctl. DO NOT EDIT.
// Source: roommanager.proto

package roommanager

import (
	"context"

	"github.com/LINKHA/automatix/app/roommanager/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRoomReq   = pb.CreateRoomReq
	CreateRoomResp  = pb.CreateRoomResp
	GetRoomInfoReq  = pb.GetRoomInfoReq
	GetRoomInfoResp = pb.GetRoomInfoResp
	JoinRoomReq     = pb.JoinRoomReq
	JoinRoomResp    = pb.JoinRoomResp
	LeaveRoomReq    = pb.LeaveRoomReq
	LeaveRoomResp   = pb.LeaveRoomResp
	MatchFinishReq  = pb.MatchFinishReq
	MatchFinishResp = pb.MatchFinishResp
	MatchRoomReq    = pb.MatchRoomReq
	MatchRoomResp   = pb.MatchRoomResp

	Roommanager interface {
		CreateRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_CreateRoomClient, error)
		JoinRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_JoinRoomClient, error)
		LeaveRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_LeaveRoomClient, error)
		MatchRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_MatchRoomClient, error)
		GetRoomInfo(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_GetRoomInfoClient, error)
		MatchFinish(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_MatchFinishClient, error)
	}

	defaultRoommanager struct {
		cli zrpc.Client
	}
)

func NewRoommanager(cli zrpc.Client) Roommanager {
	return &defaultRoommanager{
		cli: cli,
	}
}

func (m *defaultRoommanager) CreateRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_CreateRoomClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.CreateRoom(ctx, opts...)
}

func (m *defaultRoommanager) JoinRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_JoinRoomClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.JoinRoom(ctx, opts...)
}

func (m *defaultRoommanager) LeaveRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_LeaveRoomClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.LeaveRoom(ctx, opts...)
}

func (m *defaultRoommanager) MatchRoom(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_MatchRoomClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.MatchRoom(ctx, opts...)
}

func (m *defaultRoommanager) GetRoomInfo(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_GetRoomInfoClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.GetRoomInfo(ctx, opts...)
}

func (m *defaultRoommanager) MatchFinish(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_MatchFinishClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.MatchFinish(ctx, opts...)
}
