// Code generated by goctl. DO NOT EDIT.
// Source: roommanager.proto

package roommanager

import (
	"context"

	"github.com/LINKHA/automatix/app/roommanager/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRoomReq      = pb.CreateRoomReq
	CreateRoomResp     = pb.CreateRoomResp
	JoinRoomReq        = pb.JoinRoomReq
	JoinRoomResp       = pb.JoinRoomResp
	JoinRoomStreamReq  = pb.JoinRoomStreamReq
	JoinRoomStreamResp = pb.JoinRoomStreamResp

	Roommanager interface {
		CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*CreateRoomResp, error)
		JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomResp, error)
		JoinRoomStream(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_JoinRoomStreamClient, error)
	}

	defaultRoommanager struct {
		cli zrpc.Client
	}
)

func NewRoommanager(cli zrpc.Client) Roommanager {
	return &defaultRoommanager{
		cli: cli,
	}
}

func (m *defaultRoommanager) CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*CreateRoomResp, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.CreateRoom(ctx, in, opts...)
}

func (m *defaultRoommanager) JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomResp, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.JoinRoom(ctx, in, opts...)
}

func (m *defaultRoommanager) JoinRoomStream(ctx context.Context, opts ...grpc.CallOption) (pb.Roommanager_JoinRoomStreamClient, error) {
	client := pb.NewRoommanagerClient(m.cli.Conn())
	return client.JoinRoomStream(ctx, opts...)
}
