// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package rolemanager

import (
	"context"

	"github.com/LINKHA/automatix/app/friend/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendReq  = pb.AddFriendReq
	AddFriendResp = pb.AddFriendResp

	Rolemanager interface {
		AddFriend(ctx context.Context, opts ...grpc.CallOption) (pb.Rolemanager_AddFriendClient, error)
	}

	defaultRolemanager struct {
		cli zrpc.Client
	}
)

func NewRolemanager(cli zrpc.Client) Rolemanager {
	return &defaultRolemanager{
		cli: cli,
	}
}

func (m *defaultRolemanager) AddFriend(ctx context.Context, opts ...grpc.CallOption) (pb.Rolemanager_AddFriendClient, error) {
	client := pb.NewRolemanagerClient(m.cli.Conn())
	return client.AddFriend(ctx, opts...)
}
