// Code generated by goctl. DO NOT EDIT.
// Source: servermanager.proto

package usercenter

import (
	"context"

	"looklook/app/servermanager/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateServerReq  = pb.CreateServerReq
	CreateServerResp = pb.CreateServerResp
	GetServerReq     = pb.GetServerReq
	GetServerResp    = pb.GetServerResp
	Server           = pb.Server
	SetServerReq     = pb.SetServerReq
	SetServerResp    = pb.SetServerResp

	Usercenter interface {
		CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error)
		SetServer(ctx context.Context, in *SetServerReq, opts ...grpc.CallOption) (*SetServerResp, error)
		GetServer(ctx context.Context, in *GetServerReq, opts ...grpc.CallOption) (*GetServerResp, error)
	}

	defaultUsercenter struct {
		cli zrpc.Client
	}
)

func NewUsercenter(cli zrpc.Client) Usercenter {
	return &defaultUsercenter{
		cli: cli,
	}
}

func (m *defaultUsercenter) CreateServer(ctx context.Context, in *CreateServerReq, opts ...grpc.CallOption) (*CreateServerResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.CreateServer(ctx, in, opts...)
}

func (m *defaultUsercenter) SetServer(ctx context.Context, in *SetServerReq, opts ...grpc.CallOption) (*SetServerResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.SetServer(ctx, in, opts...)
}

func (m *defaultUsercenter) GetServer(ctx context.Context, in *GetServerReq, opts ...grpc.CallOption) (*GetServerResp, error) {
	client := pb.NewUsercenterClient(m.cli.Conn())
	return client.GetServer(ctx, in, opts...)
}
