// Code generated by goctl. DO NOT EDIT.
// Source: servermanager.proto

package server

import (
	"context"

	"automatix/app/servermanager/cmd/rpc/internal/logic"
	"automatix/app/servermanager/cmd/rpc/internal/svc"
	"automatix/app/servermanager/cmd/rpc/pb"
)

type ServermanagerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServermanagerServer
}

func NewServermanagerServer(svcCtx *svc.ServiceContext) *ServermanagerServer {
	return &ServermanagerServer{
		svcCtx: svcCtx,
	}
}

func (s *ServermanagerServer) CreateServer(ctx context.Context, in *pb.CreateServerReq) (*pb.CreateServerResp, error) {
	l := logic.NewCreateServerLogic(ctx, s.svcCtx)
	return l.CreateServer(in)
}

func (s *ServermanagerServer) SetServer(ctx context.Context, in *pb.SetServerReq) (*pb.SetServerResp, error) {
	l := logic.NewSetServerLogic(ctx, s.svcCtx)
	return l.SetServer(in)
}

func (s *ServermanagerServer) GetServer(ctx context.Context, in *pb.GetServerReq) (*pb.GetServerResp, error) {
	l := logic.NewGetServerLogic(ctx, s.svcCtx)
	return l.GetServer(in)
}

func (s *ServermanagerServer) LoginServer(ctx context.Context, in *pb.LoginServerReq) (*pb.LoginServerResp, error) {
	l := logic.NewLoginServerLogic(ctx, s.svcCtx)
	return l.LoginServer(in)
}
