// Code generated by goctl. DO NOT EDIT.
// Source: servermanager.proto

package server

import (
	"context"

	"looklook/app/servermanager/cmd/rpc/internal/logic"
	"looklook/app/servermanager/cmd/rpc/internal/svc"
	"looklook/app/servermanager/cmd/rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) CreateServer(ctx context.Context, in *pb.CreateServerReq) (*pb.CreateServerResp, error) {
	l := logic.NewCreateServerLogic(ctx, s.svcCtx)
	return l.CreateServer(in)
}

func (s *UsercenterServer) SetServer(ctx context.Context, in *pb.SetServerReq) (*pb.SetServerResp, error) {
	l := logic.NewSetServerLogic(ctx, s.svcCtx)
	return l.SetServer(in)
}

func (s *UsercenterServer) GetServer(ctx context.Context, in *pb.GetServerReq) (*pb.GetServerResp, error) {
	l := logic.NewGetServerLogic(ctx, s.svcCtx)
	return l.GetServer(in)
}
