// Code generated by goctl. DO NOT EDIT.
// Source: roommanager.proto

package server

import (
	"github.com/LINKHA/automatix/app/roommanager/cmd/rpc/internal/logic"
	"github.com/LINKHA/automatix/app/roommanager/cmd/rpc/internal/svc"
	"github.com/LINKHA/automatix/app/roommanager/cmd/rpc/pb"
)

type RoommanagerServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRoommanagerServer
}

func NewRoommanagerServer(svcCtx *svc.ServiceContext) *RoommanagerServer {
	return &RoommanagerServer{
		svcCtx: svcCtx,
	}
}

func (s *RoommanagerServer) CreateRoom(stream pb.Roommanager_CreateRoomServer) error {
	l := logic.NewCreateRoomLogic(stream.Context(), s.svcCtx)
	return l.CreateRoom(stream)
}

func (s *RoommanagerServer) JoinRoom(stream pb.Roommanager_JoinRoomServer) error {
	l := logic.NewJoinRoomLogic(stream.Context(), s.svcCtx)
	return l.JoinRoom(stream)
}

func (s *RoommanagerServer) LeaveRoom(stream pb.Roommanager_LeaveRoomServer) error {
	l := logic.NewLeaveRoomLogic(stream.Context(), s.svcCtx)
	return l.LeaveRoom(stream)
}

func (s *RoommanagerServer) MatchRoom(stream pb.Roommanager_MatchRoomServer) error {
	l := logic.NewMatchRoomLogic(stream.Context(), s.svcCtx)
	return l.MatchRoom(stream)
}

func (s *RoommanagerServer) GetRoomInfo(stream pb.Roommanager_GetRoomInfoServer) error {
	l := logic.NewGetRoomInfoLogic(stream.Context(), s.svcCtx)
	return l.GetRoomInfo(stream)
}

func (s *RoommanagerServer) MatchFinish(stream pb.Roommanager_MatchFinishServer) error {
	l := logic.NewMatchFinishLogic(stream.Context(), s.svcCtx)
	return l.MatchFinish(stream)
}
