// Code generated by goctl. DO NOT EDIT.
// Source: punishment.proto

package server

import (
	"github.com/LINKHA/automatix/app/punishment/cmd/rpc/internal/logic"
	"github.com/LINKHA/automatix/app/punishment/cmd/rpc/internal/svc"
	"github.com/LINKHA/automatix/app/punishment/cmd/rpc/pb"
)

type PunishmentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPunishmentServer
}

func NewPunishmentServer(svcCtx *svc.ServiceContext) *PunishmentServer {
	return &PunishmentServer{
		svcCtx: svcCtx,
	}
}

func (s *PunishmentServer) Report(stream pb.Punishment_ReportServer) error {
	l := logic.NewReportLogic(stream.Context(), s.svcCtx)
	return l.Report(stream)
}
