// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "automatix/app/login/cmd/api/internal/handler/login"
	"automatix/app/login/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/fastLogin",
				Handler: login.FastLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/enterServer",
				Handler: login.EnterServerHandler(serverCtx),
			},
		},
	)
}
