// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "automatix/app/login/cmd/api/internal/handler/login"
	"automatix/app/login/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/fastLogin",
				Handler: login.FastLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/login"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/loginServer",
				Handler: login.LoginServerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/getServerCode",
				Handler: login.GetServerCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/enterServer",
				Handler: login.EnterServerHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/login"),
	)
}
