// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"automatix/app/servermanager/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/servermanager/createServer",
				Handler: createServerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/servermanager/setServer",
				Handler: setServerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/servermanager/getServer",
				Handler: getServerHandler(serverCtx),
			},
		},
	)
}
